[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fuzz.runs = 500
evm_version = "shanghai"
ast = true
fs_permissions = [{ access = "read", path = "./blacklist.json" },{ access = "write", path = "./broadcast/" }]

[rpc_endpoints]
holesky = "${HOLESKY_RPC_URL}"
bnbtest = "${BNB_TESTNET_RPC_URL}"

[etherscan]
holesky = { key = "${ETHERSCAN_API_KEY}" }
bnbtest = { key = "${BSCSCAN_API_KEY}" }

[fmt]
multiline_func_header = "all"

# [invariant]
# fail_on_revert = false
# runs = 250
# depth = 32
