[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fuzz.runs = 500
solc_version = "0.8.21"

[fmt]
multiline_func_header = "all"

# [invariant]
# fail_on_revert = false
# runs = 250
# depth = 32
